# Generated by Django 6.0.2 on 2026-02-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('basic_salary', models.FloatField()),
                ('da_percent', models.FloatField(default=50)),
                ('hra_percent', models.FloatField(default=40)),
                ('other_percent', models.FloatField(default=10)),
                ('pf_percent', models.FloatField(default=12)),
                ('esi_percent', models.FloatField(default=0.75)),
            ],
        ),
    ]
