# Generated by Django 6.0.2 on 2026-03-04 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('year', models.IntegerField(default=2026)),
                ('leaves_taken', models.IntegerField(default=0)),
                ('manual_mode', models.BooleanField(default=False, help_text='Check this to enter values manually')),
                ('custom_earnings', models.FloatField(blank=True, default=0.0, null=True)),
                ('custom_deductions', models.FloatField(blank=True, default=0.0, null=True)),
                ('calculated_gross', models.FloatField(blank=True, null=True)),
                ('calculated_deduction', models.FloatField(blank=True, null=True)),
                ('net_salary', models.FloatField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employees.employee')),
            ],
        ),
    ]
