# Generated by Django 6.0.2 on 2026-03-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_monthlysalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='da',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='esi',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='hra',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='pf',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='manual_mode',
            field=models.BooleanField(default=False, help_text='Check to enter total values manually'),
        ),
    ]
